name: store-api

services:

  db:
    image: postgres:17.6
    hostname: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # ports:
    #   - 5432:5432
    volumes:
      - ./volume/db:/var/lib/postgresql/data

  account:
    build:
      context: ./pma252.account-service
      dockerfile: Dockerfile
    hostname: account
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    deploy:
      replicas: 1
    depends_on:
      - db

  product:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    hostname: product
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    deploy:
      replicas: 1
    depends_on:
      - db

  auth:
    build:
      context: ./pma252.auth-service
      dockerfile: Dockerfile
    hostname: auth
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}


  gateway:
    build:
      context: ./pma252.gateway-service
      dockerfile: Dockerfile
    # ports:
    #   - 8080:8080


  loadbalancer:
    image: nginx:latest
    volumes:
      - $SETUP/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - $SETUP/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise
    hostname: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - $SETUP/grafana:/var/lib/grafana
      - $SETUP/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    restart: always
